### ISSUE TITLE
Codegen optimization for `None` with type

### ISSUE THREAD

**Issue by IWANABETHATGUY** [KermanX/js_to_oxc#3]
https://kermanx.github.io/js_to_oxc/#N4IglgdgDgrgLiAXCAxgewgZzQGwKYB0OaA5gBQDkAEnjsRQDQAEAJBAIYC2eAlADoQQDEFABOpUVwCyaACZ4kcUTDzD2mOACEYYHPNFIQmWgDMC6uAH0ARjr14DwzFHaDkAZQAKAQQByIAF8gA=

for code 
```
Option::<TSTypeParameterInstantiation>::None,
```

could be simplified with: 
```
None::<TSTypeParameterInstantiation>,

```

**Comment by kermanx** [comment]
fixed in b981aad062e5ee537adc1b6edb4679d77fcc3839
